CREATE TABLE teams(
	team CHAR(3) NOT NULL,
	location VARCHAR(20) NOT NULL,
	name VARCHAR(20),
	leag CHAR(1) NOT NULL,
	PRIMARY KEY (team,leag));
CREATE TABLE players(
	ilkid VARCHAR(15) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	position CHAR(1) NOT NULL,
	firstseason INT NOT NULL,
	lastseason INT,
	h_feet INT,
	h_inches INT,
	weight INT,
	college VARCHAR(40),
	birthdate TIMESTAMP);
CREATE TABLE coaches_career(
	coachid VARCHAR(15) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	season_win INT NOT NULL,
	season_loss INT NOT NULL,
	playoff_win INT NOT NULL,
	playoff_loss INT NOT NULL,
	PRIMARY KEY (coachid));
CREATE TABLE coaches_season(
	coachid VARCHAR(15) NOT NULL,
	year INT NOT NULL,
	yr_order INT NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	season_win INT NOT NULL,
	season_loss INT NOT NULL,
	playoff_win INT NOT NULL,
	playoff_loss INT NOT NULL,
	team CHAR(3) NOT NULL,
	PRIMARY KEY (coachid,year,team));
CREATE TABLE player_playoffs(
	ilkid VARCHAR(15) NOT NULL,
	year INT NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	team CHAR(3) NOT NULL,
	leag CHAR(1),
	gp INT,
	minutes INT,
	pts INT,
	dreb INT,
	oreb INT,
	reb INT,
	asts INT,
	stl INT,
	blk INT,
	turnover INT,
	pf INT,
	fga INT,
	fgm INT,
	fta INT,
	ftm INT,
	tpa INT,
	tpm INT,
	PRIMARY KEY (ilkid,year,team,leag));
CREATE TABLE player_playoffs_career(
	ilkid VARCHAR(15) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	leag CHAR(1) NOT NULL,
	gp INT,
	minutes INT,
	pts INT,
	dreb INT,
	oreb INT,
	reb INT,
	asts INT,
	stl INT,
	blk INT,
	turnover INT,
	pf INT,
	fga INT,
	fgm INT,
	fta INT,
	ftm INT,
	tpa INT,
	tpm INT,
	PRIMARY KEY (ilkid,leag));
CREATE TABLE player_regular_season(
	ilkid VARCHAR(15) NOT NULL,
	year INT NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	team CHAR(3) NOT NULL,
	leag CHAR(1) NOT NULL,
	gp INT,
	minutes INT,
	pts INT,
	oreb INT,
	dreb INT,
	reb INT,
	asts INT,
	stl INT,
	blk INT,
	turnover INT,
	pf INT,
	fga INT,
	fgm INT,
	fta INT,
	ftm INT,
	tpa INT,
	tpm INT,
	PRIMARY KEY(ilkid,year,team,leag));
CREATE TABLE player_regular_season_career(
	ilkid VARCHAR(15) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	leag CHAR(1) NOT NULL,
	gp INT,
	minutes INT,
	pts INT,
	oreb INT,
	dreb INT,
	reb INT,
	asts INT,
	stl INT,
	blk INT,
	turnover INT,
	pf INT,
	fga INT,
	fgm INT,
	fta INT,
	ftm INT,
	tpa INT, 
	tpm INT,
	PRIMARY KEY(ilkid,leag));

